scripts/tipDeploy: handle race conditions better
Every push to cue-lang/cue master prompts a redeployment of
tip.cuelang.org. The state of this site is indicative but not critical,
so therefore we've chosen not to make a deploy failure block anything
else.

That said, we'd like to have as few failures as possible, and one
failure we've observed a couple of times has been when multiple
(possibly unrelated) commits to cue-lang/cue are submitted close
together. This causes a race in CI, where both the trybot runs that get
triggered in cue-lang/cuelang.org attempt to push to this repo's tip
branch. They both force-push (which delegates the sequencing problem to
Netlify) but a force-push can still fail - as seen in
https://github.com/cue-lang/cuelang.org/actions/runs/11915828092/job/33207028909#step:53:293:

    [master c97d0927] tip.cuelang.org: cache files for 3a55072f
     223 files changed, 663 insertions(+), 696 deletions(-)
    Pushing to https://github.com/cue-lang/cuelang.org
    POST git-receive-pack (167938 bytes)
    To https://github.com/cue-lang/cuelang.org
     ! [remote rejected]   HEAD -> tip (cannot lock ref 'refs/heads/tip': is at 650e09d1866c95b4cab162c7fc939906ab09918f but expected f9e86c07e3c7343ad467a8a067d6743ad0ff0ed8)
    error: failed to push some refs to 'https://github.com/cue-lang/cuelang.org'

This changes the script that performs that force-push to do a git-fetch
immediately before the push. This should reduce the window in which
multiple cue-lang/cue commits can cause this error from the current
duration (start-of-CI-git-checkout to git-push-origin-tip) down to the
duration of the _scripts/tipDeploy.bash script (around 1 second).

Signed-off-by: Jonathan Matthews <github@hello.jonathanmatthews.com>
Change-Id: I7674eeb128a24b51b007412711cab1cbc57e6dc3